//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HANMISYSTEM.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HANMISYSTEM.lang.MyResource", typeof(MyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOM.
        /// </summary>
        internal static string bom {
            get {
                return ResourceManager.GetString("bom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÍ MẶT HÀNG.
        /// </summary>
        internal static string cargomanagement {
            get {
                return ResourceManager.GetString("cargomanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KIỂM TRA TỒN KHO.
        /// </summary>
        internal static string checkinventory {
            get {
                return ResourceManager.GetString("checkinventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ XUẤT NHẬP.
        /// </summary>
        internal static string deliveryhistory {
            get {
                return ResourceManager.GetString("deliveryhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XUẤT KHO.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẬP KHO.
        /// </summary>
        internal static string import {
            get {
                return ResourceManager.GetString("import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUẢN LÍ VỊ TRÍ.
        /// </summary>
        internal static string locationmanagement {
            get {
                return ResourceManager.GetString("locationmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOST MANAGEMENT.
        /// </summary>
        internal static string lostmanagement {
            get {
                return ResourceManager.GetString("lostmanagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG SINGLE PART.
        /// </summary>
        internal static string ngsinglepart {
            get {
                return ResourceManager.GetString("ngsinglepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XEM TOÀN BỘ.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW LINE.
        /// </summary>
        internal static string overviewline {
            get {
                return ResourceManager.GetString("overviewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVERVIEW V2.
        /// </summary>
        internal static string overviewv2 {
            get {
                return ResourceManager.GetString("overviewv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHUẨN ĐÓNG GÓI.
        /// </summary>
        internal static string packingstandard {
            get {
                return ResourceManager.GetString("packingstandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SẢN XUẤT.
        /// </summary>
        internal static string production {
            get {
                return ResourceManager.GetString("production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LỊCH SỬ SẢN XUẤT.
        /// </summary>
        internal static string productionhistory {
            get {
                return ResourceManager.GetString("productionhistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KẾ HOẠCH SẢN XUẤT.
        /// </summary>
        internal static string productionplan {
            get {
                return ResourceManager.GetString("productionplan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BÁO CÁO.
        /// </summary>
        internal static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHẬP LẺ.
        /// </summary>
        internal static string retailimport {
            get {
                return ResourceManager.GetString("retailimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANG THÁI.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỒN KHO.
        /// </summary>
        internal static string stock {
            get {
                return ResourceManager.GetString("stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TỒN KHO THEO VỊ TRÍ.
        /// </summary>
        internal static string stockfollowlocation {
            get {
                return ResourceManager.GetString("stockfollowlocation", resourceCulture);
            }
        }
    }
}
